mappop/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

	root to: 'home#index'
	post 'home/post_sns'


	get 'privacypolicy' => 'home#privacypolicy'
	get 'rule' => 'home#rule'
	get 'help' => 'home#help'
	get 'info' => 'home#info'

	get 'login' => 'sessions#new'
	# 'sessions#new'
	post 'login' => 'sessions#create'
	delete 'logout' => 'sessions#destroy'
	get 'logout' => 'sessions#destroy'
	get '/auth/:provider/callback' => 'sessions#createSns'
	get '/auth/failure' => redirect('/')


	get 'signup' => 'users#new'
	get 'signup/:provider' => 'users#new'
	get 'users/new/:provider' => 'users#new'
	get 'users/create_on_sns/:provider' => 'users#create_on_sns'
	get 'users/new' => 'users#new'
	get 'users/token/:uuid' => 'users#token'
	get 'users/tmp'
	get 'users/all' => redirect('/') #productionで閲覧されないように
	get 'users/:id' => 'users#show'
	post 'users/upload_process'


	get 'post_images/all' => redirect('/') #productionで閲覧されないように
	post 'post_images/create'
	get 'post_images/:id' => 'post_images#show'


	resources :users
	resources :post_images


	get 'users/index'

	#404, 500エラー処理
	get '*path', controller: 'application', action: 'render_404'

end

mappop/app/models/user.rb
class User < ApplicationRecord
	
	has_secure_password

	# メール送信時に使用する
	has_many :tokens
	
end

mappop/app/controllers/users_controller.rb
class UsersController < ApplicationController
  

  def index
    @users = User.all
  end

  def show
  	@user = User.find( params[:id] )

    @img_paths = []
    jpgs = Dir.glob(Rails.root.join('public', '*.jpg'))
    jpgs.each do |png|
      @img_paths.push('/'+File.basename(png))
    end
    #@user = User.find_by( :username => params[:username] )
  end


  def new
    @user = User.new
    if params[:provider].nil?
      session.delete(:provider)
      session.delete(:uid)
    end
  end


  def all
    @users = User.all
  end


  def create
    # @user = User.new(user_params)
    tmp_user = User.find_by_email(user_params[:email])

    # if !User.find_by(:email => @user.email).nil?
    #   flash.now[:notice] = 'そのメールアドレスはすでに登録されています。'
    #   render :new
    #   return
    # end


    # ユーザ作成済み
    if tmp_user && tmp_user.created
      
      flash.alert = "入力されたメールアドレスは登録済みです。"
      redirect_to controller: 'sessions', action: 'new'
   
    # ユーザは既にあるが、本登録していない。一度トークンを全て使えなくする（するならhas_oneで上書く方がいいかもしれないが）
    elsif tmp_user
    
      @user = tmp_user
      Token.all.each do |token|
        # 有効期限を変更する
        token.update_attributes!(expired_at: Time.now)
      end
      # 新しいトークン生成
      @token = SecureRandom.uuid
      # 有効期限は２４時間
      @user.tokens.create!(uuid: @token, expired_at: 24.hours.since)
      # メール通知(ActionMailer)
      @mail = MappopMailer.send_when_update(@user,@token).deliver
      # @mail = TestMailer.user_create_mail(@user,@token).deliver
      # 仮登録成功ページヘ
      redirect_to :action => 'tmp'
    
    else
    
      @user = User.new(user_params)
      @user.created = false

      # バリデート
      if @user.email.empty?
        flash.now[:notice] = 'メールアドレスの記入は必須です。'
        render :new
        return
      end

      if @user.password.nil?
        flash.now[:notice] = 'パスワードの記入は必須です。'
        render :new
        return
      end

      # SNSのIDでの登録の場合はuidとproviderを保存
      if !session[:provider].nil?
        @user.uid = session[:uid]
        @user.provider = session[:provider]
      end

      # 画像は最初はNoImageを登録
      @user[:photo] = "docs/user_icon/no_image.jpg"
    
      # ユーザーデータ保存
      if @user.save
        # トークン生成
        @token = SecureRandom.uuid
        @user.tokens.create!(uuid: @token, expired_at: 24.hours.since)
        # メール通知
        # @mail = TestMailer.user_create_mail(@user,@token).deliver
        @mail = MappopMailer.send_when_update(@user,@token).deliver
        redirect_to :action => 'tmp'
      else
        render 'new'
      end
    end


    # respond_to do |format|
    #   if @user.save
    #     log_in @user
    #     format.html { redirect_to @user, notice: 'User was successfully created.' }
    #     format.json { render :show, status: :created, location: @user }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @user.errors, status: :unprocessable_entity }
    #   end
    # end
  end


  def tmp
  end


  def token
    # 有効期限の確認
    token = Token.find_by_uuid!(params[:uuid])
    # 有効期限を過ぎていないか確認
    if token && token.expired_at > Time.now
      # ２回目アクセスできないように更新
      token.update_attributes!(expired_at: Time.now)
      @user = token.user
      @user.update_attributes!(created: true)
      # 登録完了メール通知
      flash.now.alert = "本登録が完了しました"
      # @mail = TestMailer.user_complete_mail(@user).deliver
      # @mail = MappopMailer.user_complete_mail(@user).deliver
      # ログイン画面へ
      # redirect_to :login
      log_in @user
      format.html { redirect_to @user, notice: 'User was successfully created.' }
      format.json { render :show, status: :created, location: @user }
    else
      # トークンがない、もしくは２回目のアクセス -> 失敗を通知、ユーザ登録ページのリンクを貼る
      if token && token.user.created
        redirect_to :login, alert: "入力されたメールアドレスは本登録が完了しています。"
      else
        redirect_to :action => 'new', alert: "仮登録の有効期限が切れている。もしくは、URLが適切ではありません。"
      end
    end
  end


  def create_on_sns

      @user = User.new

      @user.name = session[:name]
      @user.uid = session[:uid]
      @user.provider = session[:provider]
      @user.photo = session[:photo]
      @user.password = session[:provider]
      @user.created = true

      # 画像は最初はNoImageを登録
      # @user.photo = "docs/user_icon/no_image.jpg"

    
      # ユーザーデータ保存
      if @user.save
        log_in @user
        redirect_to 'https://www.mapstamp.net?provider=' + session[:provider] + '&loginFlag=true'
        # redirect_to :root
      else
        str = ''
        @user.errors.each{|key, value|
          str += key.to_s + ':' + value.to_s + ', '
        }
        render plain: str
        # redirect_to '/login'
      end

  end


  def edit
    @user = User.find(params[:id])
  end



  def update
    @user = User.find(params[:id])
    
    respond_to do |format|
      if @user.update(user_params)
        format.html{ redirect_to @user, notice: 'user was successfully updated.' }
      else
        format.html{ render :show }
      end
    end
  end
  # def update
  #   @user = User.find(params[:id])
  #   # @user = User.new(user_params)
  #   # @user = User.find( params[:id] ) 
  #   # @user.photo = params[:photo]

  #   respond_to do |format|
  #     if @user.update(user_params)
  #       format.html { redirect_to @user, notice: 'User was successfully created.' }
  #       format.json { render :show, status: :created, location: @user }
  #     else
  #       format.html { render :show }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end


  def upload
  end


  def upload_process
    file = params[:upfile]
    # name = file.original_filename
    name = params[:id].to_s + '.' + file.original_filename.split('.')[1]
    perms = ['.jpg', '.jpeg', '.gif', '.png']

    if !perms.include?( File.extname( name ).downcase )
      result = 'アップロードできるのは画像ファイルのみです'
    elsif file.size > 1.megabyte
      result = 'ファイルサイズは1MBまでです。'
    else 
      File.open(Rails.root.to_s+"/public/docs/user_icon/#{name}", 'wb') { |f| f.write(file.read) }
      result = "#{name}をアップロードしました。"
    end


    user = User.find(params[:id])
    user.photo = "docs/user_icon/#{name}"
    user.save

    #render :json => tweet
    #render plain: result
    redirect_to '/users/' + params[:id].to_s
    #render plain: "id:" + params[:id]
  end
  

  def user_params
    params.require(:user).permit(:name, :username, :location, :about, :email, :password, :photo, :provider, :uid)
  end

end

mappop/app/views/users/_form.html.erb
<% flash.each do |key, value| %>
  <%= content_tag(:p, value, class: "#{key}") %>
<% end %>

<%= form_for(user) do |f| %>
	<div class="c_mb20 email">
		<%= f.label "email" %>
		<%= f.email_field :email, placeholder:"メールアドレス" %>
	</div>
	<div class="c_mb20 password">
		<%= f.label "パスワード" %>
		<%= f.password_field :password, placeholder:"パスワード（6文字以上）", minlength:"6" %>
	</div>
	<div class="c_mb20 name">
		<%= f.label "名前" %>
		<%= f.text_field :name, placeholder:"名前" %>
	</div>

	<%= f.hidden_field :username %>

	<div class="c_mb20 location">
		<%= f.label "出身地" %>
		<%= f.text_field :location %>
	</div>
	<div class="c_mb20 about">
		<%= f.label "自己紹介" %>
		<%= f.text_area :about %>
	</div>

	<%= f.submit "登録する", class:"submit_btn0 btn0" %>
	
<% end %>

mappop/app/views/users/all.html.erb
<h1>Users#all</h1>
<% if logged_in? %>
	<p>現在のログインユーザー：
	<%= User.find_by(id: session[:user_id]).name %>
	<!--<%= current_user.name %>-->
<% end %>
<% if logged_in? %>
	<%= link_to "ログアウト", logout_path, method: :delete %>
<% else %>
	<%= link_to "ログイン", login_path, method: :new %>
<% end %>
</p>

<% @users.each do |user| %>
	<h2>id:<%= user.id %></h2>
	<p>email:<%= user.email %></p>
	<p>password:<%= user.password_digest %></p>
	<p>name：<%= user.name %></p>
	<p>username：<%= user.username %></p>
	<p>location：<%= user.location %></p>
	<p>about：<%= user.about %></p>
	<p>provider:<%= user.provider %></p>
	<p>uid:<%= user.uid %></p>
	<hr>
<% end %>

mappop/app/views/users/hoge.erb
hoge

<%= link_to 'hoge', users_hoge_path() %>

mappop/app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>

mappop/app/views/users/new.html.erb
<% content_for :js_css_include do %>
<% end %>

<div class="signup_container">

	<h2 class="title0">ユーザー登録</h2>

	<%= render 'form', user:@user %>

	<%= link_to 'TwitterIDで登録', '/auth/twitter', :class => 'twitter_btn' %>

</div>

mappop/app/views/users/show.html.erb
<% content_for :js_css_include do %>
	
<% end %>

<div class="photo_container">
	<% time = Time.now.usec.to_s %>
  	<% if @user.photo.nil? %>
  		<% photo = '/docs/user_icon/no_image.jpg' %>
  	<% else %>
  		<%
  			if @user[:provider] == 'twitter' || @user[:provider] == 'facebook'
  				photo = @user.photo
  			else
  				photo = url_for_public@user.photo
  			end
  		%>
  	<% end %>
	<div class="photo" style="background-image:url(<%= photo + '?r=' + time %>);">
	</div>
	<p class="name"><%= @user[:name] %></p>
</div>


<p class="about"><%= @user[:about] %></p>

<table class="profile">
	<tr>
		<th>名前</th><td><%= @user[:name] %></td>
	</tr>
	<tr>
	<!--<li>id : <%= @user[:id] %></li>-->
	<!--<li>password : <%= @user[:password] %></li>-->
	<tr>
		<th>email</th><td><%= @user[:email] %></td>
	</tr>
	<tr>
		<th>出身地</th><td><%= @user[:location] %></td>
	</tr>
</table>

<p class="btn1 c_mb40">
	<a href="javascript:void(0);" class="edit_profile_btn btn1">プロフィールを編集</a>
</p>

<div class="modal edit_profile">
	<div class="inner">

		<div class="container">
			<div class="change_photo">
				<h3 class="title0">プロフィール画像変更</h3>
				<div class="photo_circle" style="background-image:url(<%= photo + '?r=' + time %>);">
				</div>
				<%= form_tag({ action: :upload_process }, multipart: true, class: 'photo c_mb40') do %>
					<div class="file_selector">
						<label for="file_photo" class="photo_file_select_btn">
							<%= file_field_tag :upfile, size: 50, id: 'file_photo' %>
							<p>写真選択</p>
						</label>
						<!--
						<div class="photo" style="background-image:url(<%= photo + '?r=' + time %>);">
						</div>
						-->
					</div>

					<%= hidden_field_tag :user_id, @user.id %>
					<!--<%= submit_tag '変更', class: 'photo_upload_btn btn0' %>-->
					<!--
					<a href="javascript:void(0);" class="photo_upload_btn btn0">保存</a>
					-->
				<% end %>

				<p class="btn1">
					<a href="javascript:void(0);" class="change_type_btn">プロフィール変更</a>
				</p>
			</div>

			<div class="change_profile">
				<h3 class="title0">プロフィール変更</h3>
				<%= form_for @user, html: { class: 'c_mb40' } do |f| %>
					
					<%= f.hidden_field :email %>
					<%= f.hidden_field :password %>
					<%= f.hidden_field :username %>
					<%= f.hidden_field :photo %>

					<div class="c_mb30 name clearfix">
						<%= f.label "名前" %>
						<%= f.text_field :name, maxlength: '20' %>
					</div>
					<div class="c_mb30 location clearfix">
						<%= f.label "出身地" %>
						<%= f.text_field :location, maxlength: '20' %>
					</div>
					<div class="c_mb30 about clearfix">
						<%= f.label "自己紹介" %>
						<%= f.text_area :about, maxlength: '50' %>
					</div>
					<%= f.submit "保存", class:"submit_btn btn0" %>
				<% end %>
				<p class="btn1 c_mb30">
					<a href="javascript:void(0);" class="change_type_btn">プロフィール画像変更</a>
				</p>
			</div>

		</div>
		<a href="javascript:void(0);" class="close_btn">×</a>
	</div>
</div>

mappop/app/views/users/tmp.html.erb
<h1>メールを送信しました</h1>
<p>メールを確認して下さい</p>

mappop/app/views/users/token.html.erb
token

mappop/app/views/users/upload.erb
upload

<%= link_to 'upload', users_upload_path() %>